services:
  app:
    tty: true
    networks:
      - app_network
    build:
      context: .
    ports:
      - "3000:3000"
      - "5555:5555"
    # working_dir:
    #   - /app/next-prisma-postgresql
    command:
      - npm run dev
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    depends_on:
      - db
  db:
   image: postgres:15
   hostname: db
   env_file:
     - ./next-prisma-postgresql/.env
   networks:
     - app_network
   environment:
     - TZ=Asia/Tokyo
     - POSTGRES_DB=FESNS-db
     - POSTGRES_USER=junkyo
     - POSTGRES_PASSWORD=gidaifes
     - PGDATA=/var/lib/postgresql/data/pgdata
   ports:
     - 5432:5432
   volumes:
     - db_data:/var/lib/postgresql/data
     - ./sql:/docker-entrypoint-initdb.d

networks:
 app_network:
   driver: bridge

volumes:
  db_data:
  node_modules:
